### PR TITLE
Change maintainer username from @astrofrog-conda-forge to @astrofrog

### PR DESCRIPTION
**Pull request by astrofrog**
This is to update my username from @astrofrog-conda-forge to @astrofrog - I used to have a separate username back when being a member of any conda-forge repository meant that I saw all conda-forge repositories on Travis CI but this is no longer relevant.

@conda-forge-admin please rerender

### CODE REVIEW

**Comment by ccordoba12** [comment]
No problem @astrofrog.

@dalthviz, could you check why the CI is failing? Thanks!

**Comment by dalthviz** [comment]
The error from the CI log shows: `ImportError: libGL.so.1: cannot open shared object file: No such file or directory` which usually is fixed by installing a system package like `libgl1-mesa-glx`.

Checking the commit the bot did, seems like it removed the line related with some yum requirements installation (`xorg-x11-server-Xvfb` and `gtk2-devel`) when building?:  https://github.com/conda-forge/qtpy-feedstock/pull/37/files#diff-22c5a202c93f351348030b671d6e0e1fdae11f4a23eeff71551c4ef90d88bddb

Maybe re-adding the `yum_requirements.txt` file could help? Checking I think it was removed at https://github.com/conda-forge/qtpy-feedstock/pull/36/commits/8a0df43fbda626ddd2a80706fdd672ae87a51322 (QtPy v2.3.1 PR) since seems like it was redundant but maybe that is not the case anymore?

**Comment by ccordoba12** [comment]
Yeah, please readd it and rerender the feedstock to see if that fixes the problem.

**Comment by astrofrog** [comment]
@conda-forge-admin, please rerender

**Comment by astrofrog** [comment]
@ccordoba12 @dalthviz - looks like this is passing now!

**Review by dalthviz — APPROVED** [review]
Thanks for checking the fix to the CI errors @astrofrog !

**Pull request merged**
